silent: false
autoCloseIssue: false

branchName: '${issue.title,}'
gitSafeReplacementChar: '-'

branches:
  - label: bug
    prefix: bug/
  - label: dependency
    prefix: dependency/
  - label: documentation
    prefix: documentation/
  - label: feature
    prefix: feature/
  - label: quality
    prefix: quality/
  - label: workflow
    prefix: workflow/
  - label: hotfix
    prefix: hotfix/
    name: master
  - label: '*'
    prefix: issue/
