silent: false
autoCloseIssue: true
branchName: 'issue-${issue.number}-${issue.title}'
branches:
  - label: bug
    prefix: bug/
  - label: dependency
    prefix: dependency/
  - label: documentation
    prefix: documentation/
  - label: feature
    prefix: feature/
  - label: hotfix
    prefix: hotfix/
    name: master
  - label: quality
    prefix: quality/
  - label: '*'
    prefix: issues/
